In [1]:
import numpy as np 

### Question 1 : 

In [2]:
arr =np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### Question 2 : 

In [35]:
arr = np.array([1.5, 2.6, 3.7])
print(type(arr))
print(arr.dtype)

<class 'numpy.ndarray'>
float64


In [36]:
arr = np.array([1.5 , 2.6 , 3.7], dtype=np.float64)
print(arr.dtype)
print(arr)

float64
[1.5 2.6 3.7]


### Question 3 : 

In [39]:
arr = np.array([2+3j ,3-2j ,4+6j] , dtype=np.complex128)
print(arr)
print(type(arr))
print(arr.dtype)

[2.+3.j 3.-2.j 4.+6.j]
<class 'numpy.ndarray'>
complex128


### Question 4 : 

In [41]:
arr1 = np.array([1,2,3,4] , dtype = np.float32)
print(arr1.dtype)


float32


### Question 5 : 

In [42]:
arr = np.array([1.0, 2.0, 3.0, 4.0], dtype=np.float64)
print(arr.dtype)
# Convert to float32
arr1 = arr.astype(np.float32)

print(arr1)
print(arr1.dtype)

float64
[1. 2. 3. 4.]
float32


### Question 6 : Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

In [71]:
def array_attributes(arr) : 
    
    
    shape = arr.shape 
    size = arr.size 
    data_type = arr.dtype
    
    
    return shape , size , data_type



array = np.array([[1,2,3,4],[1,2,3,4]] )

shape , size , data_type = array_attributes(arr)

print("the shape of the array is : ", shape )
print("the size of the array is :" , size)
print("the datatype of the array is : " ,data_type)




# array = np.array([[1,2,3,4],[1,2,3,4]])
# print(array)
# print(array.shape)
# print(array.size)
# print(array.dtype)

the shape of the array is :  (2, 3)
the size of the array is : 6
the datatype of the array is :  int32


### Question 7 : Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [49]:
array = np.array([[1,2,3,4],[1,2,3,4]])
print(array.ndim)

2


### Question 8 :  Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.


In [53]:
item_size_info = np.array([1,2,3,4])
print(item_size_info.nbytes)
print(item_size_info.size)

16
4


### Question 9 :  Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [57]:
def array_strides(arr):
    return arr.strides

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
strides = array_strides(arr)
print("Strides of the array:", strides)

Strides of the array: (12, 4)


In [60]:
# arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
# print(" strides of the array is : ",arr.strides)

 strides of the array is :  (12, 4)


### Question 10 :  Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array

In [64]:
# arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
# print(" strides of the array is : ",arr.strides)
# print("size of the array is : " ,arr.shape) 

In [66]:
def array(arr):
    return arr.strides , arr.shape

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
strides = array(arr)
print("Strides of the array & Shape of the array  is : ", strides) 


Strides of the array & Shape of the array  is :  ((12, 4), (2, 3))


### Question 11 :  Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

In [72]:
def create_zeros_array(n):
    zeros_array = np.zeros(n)
    return zeros_array

# Example usage:
n = 5
zeros_array = create_zeros_array(n)
print("Array of zeros with", n, "elements:", zeros_array)


Array of zeros with 5 elements: [0. 0. 0. 0. 0.]


In [74]:
def create_ones_array(n):
    return np.ones(n) 

print(create_ones_array(5))


[1. 1. 1. 1. 1.]


###  12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.

In [84]:
def create_one_matrix(i,j):
    ones_array = np.ones((i,j))
    return ones_array 
i = 2 
j = 2  

ones_array =  create_one_matrix(i,j)
print("Matrix of ones with size",i, "x", j , ":\n", ones_array)

Matrix of ones with size 2 x 2 :
 [[1. 1.]
 [1. 1.]]


### 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
### creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified step 

# 

In [86]:
import numpy as np

def generate_range_array(start, stop, step):
    range_array = np.arange(start, stop, step)
    return range_array

# Example usage:
start = 1
stop = 10
step = 2
range_array = generate_range_array(start, stop, step)
print("Range array from", start, "to", stop, "with step", step, ":\n", range_array)


Range array from 1 to 10 with step 2 :
 [1 3 5 7 9]


### 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).

In [87]:
import numpy as np

def generate_linear_space(start, stop, num):
    linear_space_array = np.linspace(start, stop, num)
    return linear_space_array

# Example usage:
start = 1.0
stop = 10.0
num = 5
linear_space_array = generate_linear_space(start, stop, num)
print("Linear space array from", start, "to", stop, "with", num, "values:\n", linear_space_array)


Linear space array from 1.0 to 10.0 with 5 values:
 [ 1.    3.25  5.5   7.75 10.  ]


### 15 Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
 ### identity matrix of size `n x n` using `numpy.eye`

In [92]:
# def  create_identity_matrix(n):
    
#     return np.eye

# n = 3 
    
# print(create_identity_matrix(3)) 

def create_identity_matrix(n):
    identity_matrix = np.eye(n)
    return identity_matrix

# Example usage:
n = 4
identity_matrix = create_identity_matrix(n)
print(f"Identity matrix of size {n} x {n}:\n{identity_matrix}")


Identity matrix of size 4 x 4:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 16. Write a function that takes a Python list and converts it into a NumPy array

In [94]:
# array = np.array([1,2,3,4])
# print(type(array))

def list_to_numpy_array(py_list):
    np_array = np.array(py_list)
    return np_array

# Example usage:
python_list = [1, 2, 3, 4]
array = list_to_numpy_array(python_list)
print("Type of array:", type(array))


Type of array: <class 'numpy.ndarray'>


### 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

In [96]:
# Create a NumPy array
original_array = np.array([[1, 2, 3], [4, 5, 6]])

# Create a view of the original array
view_array = original_array.view()

# Modify the view array (this modifies the original array as well)
view_array[0, 0] = 100

# Print original array and view array
print("Original array:\n", original_array)
print("View array:\n", view_array)


Original array:
 [[100   2   3]
 [  4   5   6]]
View array:
 [[100   2   3]
 [  4   5   6]]


# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [104]:
def function(arr1,arr2): 
    arr = np.concatenate((arr1,arr2) , axis = 0 ) 
    return arr 
arr1 = [[1,2,3],[4,6,7]]
arr2 = [[2,3,4],[4,5,6]]

array = function(arr1,arr2)
print(array)
print()
print(arr1)
print(arr2)

[[1 2 3]
 [4 6 7]
 [2 3 4]
 [4 5 6]]

[[1, 2, 3], [4, 6, 7]]
[[2, 3, 4], [4, 5, 6]]


In [105]:
def function(arr1,arr2): 
    arr = np.concatenate((arr1,arr2) , axis = 1) 
    return arr 
arr1 = [[1,2,3],[4,6,7]]
arr2 = [[2,3,4],[4,5,6]]

array = function(arr1,arr2)
print(array)
print()
print(arr1)
print(arr2)

[[1 2 3 2 3 4]
 [4 6 7 4 5 6]]

[[1, 2, 3], [4, 6, 7]]
[[2, 3, 4], [4, 5, 6]]


### Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy. concatenate`

In [109]:
def function(arr1,arr2): 
    arr = np.concatenate((arr1,arr2) , axis = 0 ) 
    return arr 
arr1 = [[1,2,3]]
arr2 = [[2,3,4],[4,5,6]]

array = function(arr1,arr2)
print(array)
print()
print(arr1)
print(arr2)

[[1 2 3]
 [2 3 4]
 [4 5 6]]

[[1, 2, 3]]
[[2, 3, 4], [4, 5, 6]]


# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [110]:
import numpy as np

def stack_arrays_vertically(arrays):
    """
    Vertically stacks multiple NumPy arrays given as a list.

    Parameters:
    - arrays: List of NumPy arrays to be vertically stacked

    Returns:
    - Vertically stacked NumPy array
    """
    stacked_array = np.vstack(arrays)
    return stacked_array

# Example usage:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
array3 = np.array([[13, 14, 15]])

# Stack arrays vertically
stacked_array = stack_arrays_vertically([array1, array2, array3])
print("Vertically stacked array:\n", stacked_array)


Vertically stacked array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

In [111]:
import numpy as np

def create_integer_array(start, stop, step):
    """
    Create a NumPy array of integers within a specified range (inclusive) with a given step size.

    Parameters:
    - start: Starting value of the range (inclusive)
    - stop: Ending value of the range (inclusive)
    - step: Step size between each pair of consecutive values

    Returns:
    - NumPy array of integers within the specified range
    """
    arr = np.arange(start, stop + 1, step, dtype=int)
    return arr

# Example usage:
start = 1
stop = 10
step = 2

array = create_integer_array(start, stop, step)
print("Array of integers:", array)


Array of integers: [1 3 5 7 9]


### 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

In [113]:
def fun():
    return np.linspace(0,1,10)

array = fun()
print(array)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


### 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

In [115]:
def fun():
    arr = np.logspace(1,3,5)
    return arr

array = fun()
print(array)

[  10.           31.6227766   100.          316.22776602 1000.        ]


In [116]:
# def multiply(x,y=2):
#     return x*y 
# result = multiply(3)
# print(result)

6


### 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

In [118]:
import numpy as np
import pandas as pd

def create_random_dataframe():
    """
    Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns,
    with values being random integers between 1 and 100.

    Returns:
    - Pandas DataFrame with random integers between 1 and 100
    """
    # Generate a NumPy array with random integers between 1 and 100
    random_array = np.random.randint(1, 101, size=(5, 3))
    
    # Create a Pandas DataFrame from the NumPy array
    df = pd.DataFrame(random_array, columns=['Column1', 'Column2', 'Column3'])
    
    return df

# Example usage:
dataframe = create_random_dataframe()
print("Pandas DataFrame with random integers between 1 and 100:\n", dataframe)


Pandas DataFrame with random integers between 1 and 100:
    Column1  Column2  Column3
0       19       68       23
1        4       93       64
2       19       40       91
3        8       14       38
4       82       49       41


### 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

In [119]:
import pandas as pd
import numpy as np

def replace_negatives_with_zeros(df, column_name):
    """
    Replace all negative values in a specific column of a Pandas DataFrame with zeros.

    Parameters:
    - df: Pandas DataFrame
    - column_name: Name of the column to process

    Returns:
    - Pandas DataFrame with negative values replaced by zeros in the specified column
    """
    # Ensure the specified column exists in the DataFrame
    if column_name in df.columns:
        # Use NumPy to replace negative values with zeros
        df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    else:
        print(f"Column '{column_name}' does not exist in the DataFrame.")
    
    return df

# Example usage:
data = {'A': [1, -2, 3, -4, 5], 'B': [-1, 2, -3, 4, -5]}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

# Replace negative values in column 'A'
df = replace_negatives_with_zeros(df, 'A')
print("\nDataFrame after replacing negative values in column 'A':\n", df)


Original DataFrame:
    A  B
0  1 -1
1 -2  2
2  3 -3
3 -4  4
4  5 -5

DataFrame after replacing negative values in column 'A':
    A  B
0  1 -1
1  0  2
2  3 -3
3  0  4
4  5 -5


# 26. Access the 3rd element from the given NumPy array

In [120]:
arr = np.array([10, 20, 30, 40, 50])
arr[2]

30

# 27. Retrieve the element at index (1, 2) from the 2D NumPy array.

In [123]:
arr = np.array([[1, 2, 3], [4, 5, 6] , [7, 8, 9]]) 
arr[1,2]

6

# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.

In [126]:
arr = np.array([3, 8, 2, 10, 5, 7])
arr > 5

array([False,  True, False,  True, False,  True])

# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array

In [128]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[2:5])

[3 4 5]


# 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

In [138]:
import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

sub_array = arr_2d[:2, 1:]
print(sub_array)


[[2 3]
 [5 6]]


# 31.Write a NumPy function to extract elements in specific order from a given       2D array based on indices provided in another array

In [145]:
import numpy as np

def extract_elements(arr, indices):
    """
    Extract elements from a 2D array `arr` based on indices provided in `indices`.
    
    Parameters:
    arr (np.ndarray): Input 2D array from which elements will be extracted.
    indices (np.ndarray): 2D array of indices specifying the elements to extract.
    
    Returns:
    np.ndarray: Extracted elements from `arr` based on `indices`.
    """
    rows = indices[:, 0]
    cols = indices[:, 1]
    extracted_elements = arr[rows, cols]
    return extracted_elements

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

indices = np.array([[0, 1],
                    [1, 2]])

result = extract_elements(arr_2d, indices)
print("Extracted elements based on indices:")
print(result)


Extracted elements based on indices:
[2 6]


# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

In [146]:
import numpy as np

def filter_greater_than(arr, threshold):
    """
    Filter elements greater than a threshold from a given 1D array using boolean indexing.
    
    Parameters:
    arr (np.ndarray): Input 1D NumPy array to filter.
    threshold (float or int): Threshold value for comparison.
    
    Returns:
    np.ndarray: Filtered array containing elements greater than the threshold.
    """
    filtered_array = arr[arr > threshold]
    return filtered_array

arr = np.array([1, 5, 3, 8, 2, 10, 7])
threshold = 5

filtered_result = filter_greater_than(arr, threshold)
print("Filtered elements greater than", threshold, ":")
print(filtered_result)


Filtered elements greater than 5 :
[ 8 10  7]


# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

In [147]:
import numpy as np

def extract_elements_3d(arr, indices_dim1, indices_dim2, indices_dim3):
    """
    Extract specific elements from a 3D array `arr` using indices provided in three separate arrays
    corresponding to each dimension.
    
    Parameters:
    arr (np.ndarray): Input 3D NumPy array from which elements will be extracted.
    indices_dim1 (np.ndarray): 1D array of indices for the first dimension.
    indices_dim2 (np.ndarray): 1D array of indices for the second dimension.
    indices_dim3 (np.ndarray): 1D array of indices for the third dimension.
    
    Returns:
    np.ndarray: Extracted elements from `arr` based on provided indices.
    """
    extracted_elements = arr[indices_dim1, indices_dim2, indices_dim3]
    return extracted_elements

arr_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

indices_dim1 = np.array([0, 1])
indices_dim2 = np.array([0, 1])
indices_dim3 = np.array([1, 2])

result = extract_elements_3d(arr_3d, indices_dim1, indices_dim2, indices_dim3)
print("Extracted elements from 3D array:")
print(result)


Extracted elements from 3D array:
[ 2 12]


# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

In [148]:
import numpy as np

def filter_with_conditions(arr, condition1, condition2):
    """
    Return elements from an array `arr` where both conditions are satisfied using boolean indexing.
    
    Parameters:
    arr (np.ndarray): Input NumPy array to filter.
    condition1 (np.ndarray): Boolean array for the first condition.
    condition2 (np.ndarray): Boolean array for the second condition.
    
    Returns:
    np.ndarray: Filtered array containing elements satisfying both conditions.
    """
    filtered_array = arr[(condition1) & (condition2)]
    return filtered_array

arr = np.array([1, 5, 3, 8, 2, 10, 7])
condition1 = arr > 3
condition2 = arr % 2 == 0

filtered_result = filter_with_conditions(arr, condition1, condition2)
print("Filtered elements where both conditions are satisfied:")
print(filtered_result)


Filtered elements where both conditions are satisfied:
[ 8 10]


# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays

In [150]:
import numpy as np

def extract_elements_2d(arr, row_indices, col_indices):
    """
    Extract elements from a 2D array `arr` using row and column indices provided in separate arrays.
    
    Parameters:
    arr (np.ndarray): Input 2D NumPy array from which elements will be extracted.
    row_indices (np.ndarray): 1D array of row indices.
    col_indices (np.ndarray): 1D array of column indices.
    
    Returns:
    np.ndarray: Extracted elements from `arr` based on provided row and column indices.
    """
    extracted_elements = arr[row_indices, col_indices]
    return extracted_elements

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 1])

result = extract_elements_2d(arr_2d, row_indices, col_indices)
print("Extracted elements from 2D array:")
print(result)


Extracted elements from 2D array:
[2 6 8]


# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [157]:
arr = np.array([[1,2,3],[2,3,4],[4,5,6]])
print("original array is ") 
print(arr)
result = arr+5
print("now new array is " )
print(result)

original array is 
[[1 2 3]
 [2 3 4]
 [4 5 6]]
now new array is 
[[ 6  7  8]
 [ 7  8  9]
 [ 9 10 11]]


# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

In [172]:
arr1 = np.array([[1,2,3]])
arr2 = np.array([[3,4,4,4],[2,3,4,5],[5,6,7,9]]) 
# print(arr1.shape)
# print(arr2.shape)
# result = arr1 * arr2 
# print(result)

arr1_transposed = arr1.T  

result = arr2 * arr1_transposed

print("arr1 shape:", arr1.shape)
print("arr2 shape:", arr2.shape)
print("Result of element-wise multiplication:")
print(result)

arr1 shape: (1, 3)
arr2 shape: (3, 4)
Result of element-wise multiplication:
[[ 3  4  4  4]
 [ 4  6  8 10]
 [15 18 21 27]]


# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

In [176]:
arr = np.array([1,2,4,3])
arr1 = np.array([[2,2,3],[3,3,3],[1,2,3],[2,3,4]])
array1 = arr1.T
print(arr+array1)
print(arr.shape)
print(arr1.shape)

[[3 5 5 5]
 [3 5 6 6]
 [4 5 7 7]]
(4,)
(4, 3)


# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

In [182]:
arr = np.array([[2],[2],[2]]) 
arr1 = np.array([[1,2,3]])

print(arr.shape)
print(arr1.shape)
print(arr.T + arr1)

(3, 1)
(1, 3)
[[3 4 5]]


# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

In [190]:
import numpy as np

arr1 = np.array([[2, 3, 4],
                 [2, 3, 4]])  # Shape (2, 3)
arr2 = np.array([[2, 2],
                 [2, 2]])  # Shape (2, 2)

# Reshape arr2 to match dimensions with arr1 for broadcasting
arr2_reshaped = arr2.reshape(2, 2, 1)  # Shape (2, 2, 1)

# Perform multiplication using broadcasting
result = arr1 * arr2_reshaped

print("arr1 shape:", arr1.shape)
print("arr2 shape after reshaping:", arr2_reshaped.shape)
print("Result of multiplication using broadcasting:")
print(result)


arr1 shape: (2, 3)
arr2 shape after reshaping: (2, 2, 1)
Result of multiplication using broadcasting:
[[[4 6 8]
  [4 6 8]]

 [[4 6 8]
  [4 6 8]]]


# 41. Calculate column wise mean for the given array:

In [192]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
column_wise_mean = np.mean(arr,axis=0)
print(column_wise_mean)

[2.5 3.5 4.5]


# 42. Find maximum value in each row of the given array:

In [193]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
max_value = np.max(arr,axis=1)
print(max_value)

[3 6]


# 43. For the given array, find indices of maximum value in each column.

In [197]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
# Find indices of maximum value in each column
max_indices = np.argmax(arr, axis=0)

print("Original array:")
print(arr)
print("\nIndices of maximum value in each column:")
print(max_indices)


Original array:
[[1 2 3]
 [4 5 6]]

Indices of maximum value in each column:
[1 1 1]


# 44. For the given array, apply custom function to calculate moving sum along rows.

In [2]:
import numpy as np 

In [5]:
# arr = np.array([[1, 2, 3], [4, 5, 6]])
# arr1 = np.concatenate(arr,axis=0)
# print(arr1)

[1 2 3 4 5 6]


In [7]:
# arr = np.array([[1, 2, 3], [4, 5, 6]])
# arr1 = np.cumsum(arr,axis=1)
# print(arr1)

[[ 1  3  6]
 [ 4  9 15]]


In [8]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr1 = arr.flatten()
print("Concatenated array:", arr1)

moving_sum = np.cumsum(arr1)
print("Moving sum:", moving_sum)


Concatenated array: [1 2 3 4 5 6]
Moving sum: [ 1  3  6 10 15 21]


In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr1 =arr.flatten()
arr2 = np.cumsum(arr1,axis=0)
print(arr1)
print(arr2)

[1 2 3 4 5 6]
[ 1  3  6 10 15 21]


# 45. In the given array, check if all elements in each column are even.

In [14]:
arr = np.array([[2, 4, 6],
                [3, 5, 7]])
arr1 = np.all(arr%2 == 0 , axis=0)   

In [15]:
print(arr1)

[False False False]


In [16]:
# when we are dealing with 2d array : axis = 0 > column and axis = 1 > rows 

# 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix

In [19]:
original_array = np.array([1, 2, 3, 4, 5, 6])
original_array.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# 47. Create a function that takes a matrix as input and returns the flattened array

In [24]:
def function(input_matrix):
    return  input_matrix.flatten()
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(function(input_matrix))

[1 2 3 4 5 6]


# 48. Write a function that concatenates two given arrays along a specified axis.

In [26]:
array1 = np.array([[1, 2], 
                   [3, 4]])
array2 = np.array([[5, 6],
                   [7, 8]])

array3 = np.concatenate((array1,array2),axis=1)
print(array3)

[[1 2 5 6]
 [3 4 7 8]]


# 49. Create a function that splits an array into multiple sub-arrays along a specified axis.

In [32]:
def function(arr):
    
    return arr 

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr = np.array_split(original_array,3)
print(function(arr))

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


# 50. Write a function that inserts and then deletes elements from a given array at specified indices.

In [33]:
def modify_array(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    # Insert elements at specified indices
    modified_array = np.insert(original_array, indices_to_insert, values_to_insert)
    
    # Delete elements at specified indices
    modified_array = np.delete(modified_array, indices_to_delete)
    
    return modified_array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

result = modify_array(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(result)


[ 1 10  4 11  5]


# 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

In [39]:
arr1 = np.array([[1,2,3],
                [1,2,3],
                [1,2,3]])
arr2 = np.array([[1,2,3],
                [1,2,3],
                [1,2,3]])

arr3 = arr1 + arr2
print(arr3)

[[2 4 6]
 [2 4 6]
 [2 4 6]]


# 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [40]:
import numpy as np

# Generate arr1 with sequential integers from 10 to 1
arr1 = np.arange(10, 0, -1)

# Generate arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)

# Subtract arr2 from arr1 element-wise
result = arr1 - arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Result of arr1 - arr2:", result)


arr1: [10  9  8  7  6  5  4  3  2  1]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Result of arr1 - arr2: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


# 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.

In [42]:
import numpy as np

# Generate arr1 with random integers
arr1 = np.random.randint(1, 10, size=(5,))  # Example: random integers from 1 to 10, shape (5,)

# Generate arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)

# Perform element-wise multiplication between arr1 and arr2
result = arr1 * arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise multiplication result:", result)


arr1: [7 3 4 9 3]
arr2: [1 2 3 4 5]
Element-wise multiplication result: [ 7  6 12 36 15]


# 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

In [48]:
arr1 = np.arange(2,11,2)
print(arr1)
arr2 = np.arange(1,6)
print(arr2)
arr3 = arr1/arr2
print("element wise divison of arr1 and arr2 : ", arr3)

[ 2  4  6  8 10]
[1 2 3 4 5]
element wise divison of arr1 and arr2 :  [2. 2. 2. 2. 2.]


and if i want the output in integer so you  will use "//" this make the round of any float value to integer

In [49]:
arr1 = np.arange(2,11,2)
print(arr1)
arr2 = np.arange(1,6)
print(arr2)
arr3 = arr1//arr2
print("element wise divison of arr1 and arr2 : ", arr3)

[ 2  4  6  8 10]
[1 2 3 4 5]
element wise divison of arr1 and arr2 :  [2 2 2 2 2]


# 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [57]:
arr1 = np.arange(1,6)
arr2 = np.arange(5,0,-1)
print(arr1)
print(arr2)
arr3 = (arr1**arr2)
print(arr3)

[1 2 3 4 5]
[5 4 3 2 1]
[ 1 16 27 16  5]


# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

In [58]:
import numpy as np

def count_substring_occurrences(arr, substring):
    count = 0
    for string in arr:
        count += string.count(substring)
    return count

# Example usage:
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
result = count_substring_occurrences(arr, substring)
print(f"Occurrences of '{substring}' in the array: {result}")



Occurrences of 'hello' in the array: 3


# 57. Write a function that extracts uppercase characters from a NumPy array of strings.


In [59]:
def extract_uppercase_chars(arr):
    uppercase_chars = []
    for string in arr:
        for char in string:
            if char.isupper():
                uppercase_chars.append(char)
    return uppercase_chars

# Example usage:
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
result = extract_uppercase_chars(arr)
print("Uppercase characters:", result)


Uppercase characters: ['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']


# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

In [60]:
import numpy as np

def replace_substring(arr, old_substring, new_substring):
    return np.char.replace(arr, old_substring, new_substring)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
new_arr = replace_substring(arr, 'apple', 'orange')
print("Modified array:", new_arr)


Modified array: ['orange' 'banana' 'grape' 'pineorange']


# 59. Write a function that concatenates strings in a NumPy array element-wise.

In [69]:
def function(arr1,arr2):
    arr3=np.char.add(arr1,arr2)
    return arr3
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
print(function(arr1,arr2))


['HelloOpen' 'WorldAI']


# 60. Write a function that finds the length of the longest string in a NumPy array.



In [70]:
import numpy as np

def longest_string_length(arr):
    # Vectorize the len function to apply it element-wise to the array
    v_len = np.vectorize(len)
    
    # Apply the len function to each element in the array and find the maximum length
    max_length = np.max(v_len(arr))
    
    return max_length

# Example usage:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print("Length of the longest string:", longest_string_length(arr))


Length of the longest string: 9


# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

In [13]:
ar=np.random.randint(1,1000,100)
print(ar)
print()
print("mean of the dataset is:" , np.mean(ar))
print("median of the dataset is:" , np.median(ar))
print("standard deviation of the dataset is:" , np.std(ar))
print("variance of the dataset is:" , np.var(ar))


[961 444  91 297 491 995 544 126 848 313 687 397 154 692 925  79 900 138
 640 814 243 864 554 948 401 622 983  50 792 688 901  57  81 835 768 689
  92 793 470 713 483 325 190 411  91 719 915 170 856 864 721  37 863  76
 468 667  22  92 507 234 659   1 859 770 104 957 711 443 781 118 110 886
 323 866 243 642 114 417  53 377 464 841 809 528 711 591 709 410  31 661
 851 163 848  14 114 935 911 629 754  64]

mean of the dataset is: 512.63
median of the dataset is: 549.0
standard deviation of the dataset is: 314.4707825856005
variance of the dataset is: 98891.87310000001


# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

In [17]:
arr=np.random.randint(1,100,50)
print(arr)
arr1 = np.percentile(arr,25)
arr2 = np.percentile(arr,75)
print("25th percentilesis:", arr1)
print("75th percentiles is : " , arr2)

[40 21 24 64 71 66 73 38 60 10 77 27  2 72 92 31  4 88 69 84 69 71 24 84
  5  8 47 16 33 12 63 77 20 41 39 44 16 61 66 64 88 66 39 68 84 75 28  7
 35 14]
25th percentilesis: 24.0
75th percentiles is :  70.5


# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

In [18]:
import numpy as np

# Create two arrays representing two sets of variables
array1 = np.random.rand(50)  # Array of 50 random numbers between 0 and 1
array2 = np.random.rand(50)  # Another array of 50 random numbers between 0 and 1

# Compute the correlation coefficient between these arrays
correlation_matrix = np.corrcoef(array1, array2)

print("Array 1: ", array1)
print("Array 2: ", array2)
print("Correlation Coefficient Matrix: \n", correlation_matrix)


Array 1:  [0.23699927 0.11379823 0.32711291 0.66856855 0.45647371 0.30022209
 0.15869898 0.68584534 0.42106484 0.07488209 0.07007491 0.1287491
 0.72114158 0.73040321 0.495104   0.69400147 0.34392825 0.09925766
 0.86219034 0.58073752 0.97717901 0.21977481 0.82124555 0.21247313
 0.77774726 0.26079836 0.11458488 0.19264168 0.04554823 0.38965441
 0.46821627 0.20974204 0.12785703 0.50968951 0.62986139 0.20140448
 0.14430119 0.13378878 0.05801705 0.5593905  0.30551951 0.56291731
 0.97696225 0.69803938 0.53476095 0.67831109 0.17152319 0.53678291
 0.07484022 0.22070384]
Array 2:  [0.65203442 0.57671924 0.8598541  0.07963652 0.59132136 0.46019699
 0.9514009  0.41856585 0.96497682 0.4524699  0.92132265 0.15766603
 0.77696068 0.71274456 0.9420676  0.63766186 0.440956   0.1983204
 0.47383679 0.35461817 0.39074976 0.4410836  0.75491006 0.34906272
 0.44915139 0.70107838 0.59327756 0.01382874 0.76911106 0.32057632
 0.62976213 0.44862772 0.01873497 0.17841457 0.04889346 0.6332082
 0.5437785  0.5683353

# 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

In [22]:
import numpy as np

# Create two matrices
matrix1 = np.array([[1, 2, 3], 
                    [4, 5, 6]])

matrix2 = np.array([[7, 8], 
                    [9, 10], 
                    [11, 12]])

# Perform matrix multiplication
result = np.dot(matrix1, matrix2)

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print(matrix1.shape)
print(matrix2.shape)
print()
print("Result of Matrix Multiplication:\n", result)
print(result.shape)


Matrix 1:
 [[1 2 3]
 [4 5 6]]
Matrix 2:
 [[ 7  8]
 [ 9 10]
 [11 12]]
(2, 3)
(3, 2)

Result of Matrix Multiplication:
 [[ 58  64]
 [139 154]]
(2, 2)


# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles

In [36]:
arr = np.random.randint(10,1000,50)
print(arr)
print()
arr1 = np.percentile(arr,90)
arr2=np.percentile(arr,10)
arr3=np.percentile(arr,50)

quartile_1 = np.percentile(arr,25)
quartile_3 = np.percentile(arr,75)

print("this is 90 percentile:",arr1)
print("this is 10 percentile:",arr2)
print("this is 50 percentile : ", arr3)
print()
print("quarter_1:" , quartile_1)
print("quarter_3:", quartile_3)


[363 391 950 144 433 835 967 592 238 864 254 369 761 802 936  76 143 673
 999  11 765 787 964 101 902 747 394 935 689 170 855 745 588 825 449  95
 569 208 651 327 937 477 582 515 249 581 366 615 675 253]

this is 90 percentile: 936.1
this is 10 percentile: 143.9
this is 50 percentile :  585.0

quarter_1: 336.0
quarter_3: 798.25


# 66. Create a NumPy array of integers and find the index of a specific element.

In [38]:
import numpy as np

# Create a NumPy array of integers
arr = np.array([1, 2, 3, 4, 3, 5, 6, 7, 8, 9, 9])

# Find the index of a specific element, for example, the element '3'
element_to_find = 3
indices = np.where(arr == element_to_find)

print("Array:", arr)
print(f"Indices of element {element_to_find}:", indices[0])


(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 5, 6, 7, 8, 9], dtype=int64))


# 67. Generate a random NumPy array and sort it in ascending order.

In [39]:
import numpy as np

# Generate a random NumPy array with 10 elements between 0 and 100
random_array = np.random.randint(0, 100, size=10)

# Sort the array in ascending order
sorted_array = np.sort(random_array)

print("Random Array:", random_array)
print("Sorted Array:", sorted_array)


Random Array: [76 27 34 71  2 61 41 86 57 35]
Sorted Array: [ 2 27 34 35 41 57 61 71 76 86]


# 68. Filter elements >20  in the given NumPy array.

In [40]:
import numpy as np

# Create a NumPy array
arr = np.array([12, 25, 6, 42, 8, 30])

# Filter elements greater than 20
filtered_array = arr[arr > 20]

print("Original Array:", arr)
print("Filtered Array (elements > 20):", filtered_array)


Original Array: [12 25  6 42  8 30]
Filtered Array (elements > 20): [25 42 30]


# 69. Filter elements which are divisible by 3 from a given NumPy array.

In [42]:
arr = np.array([1, 5, 8, 12, 15])
filtered_array = arr[arr%3==0]
print("original array" , arr)
print("filtered array (which is divisible by 3 ): ", filtered_array)

original array [ 1  5  8 12 15]
filtered array (which is divisible by 3 ):  [12 15]


# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.

In [46]:
arr = np.array([10, 20, 30, 40, 50])
filter_element = arr[(arr>=20)&(arr<=40)]
print("original array is : " , arr)
print("after filter (when condition is applied) : " , filter_element)

original array is :  [10 20 30 40 50]
after filter (when condition is applied) :  [20 30 40]


# 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

In [47]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3])

# Check the byte order using the dtype attribute's byteorder property
byte_order = arr.dtype.byteorder

print("Original Array:", arr)
print("Byte Order:", byte_order)


Original Array: [1 2 3]
Byte Order: =


# 72. For the given NumPy array, perform byte swapping in place using `byteswap()`.

In [48]:
import numpy as np

# Define the NumPy array with dtype int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Perform byte swapping in place
arr.byteswap(True)

# Print the modified array
print("Modified array after byte swapping:", arr)


Modified array after byte swapping: [16777216 33554432 50331648]


# 73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.

In [49]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

# Swap byte order without modifying original array
arr_swapped = arr.newbyteorder()

# Print the original and swapped arrays
print("Original array:")
print(arr)
print("Swapped byte order array:")
print(arr_swapped)


Original array:
[1 2 3]
Swapped byte order array:
[16777216 33554432 50331648]


# 74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.

In [50]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

# Check system endianness
if arr.dtype.byteorder == '=':  # '=' means native byte order
    # Swap byte order if not native
    arr = arr.newbyteorder()

print("Original Array:", arr)


Original Array: [16777216 33554432 50331648]


# 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.

In [51]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

byte_order = arr.dtype.byteorder

if byte_order == '=':
    print("No byte swapping necessary (native byte order)")
else:
    print(f"Byte swapping necessary: Current byte order is '{byte_order}'")


No byte swapping necessary (native byte order)


# 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [61]:
import numpy as np

# Create arr1 with values from 1 to 10
arr1 = np.arange(1, 11)

# Create a copy of arr1
copy_arr = arr1.copy()

# Modify an element in copy_arr
copy_arr[0] = 100

# Check if modifying copy_arr affects arr1
print("Original arr1:", arr1)
print("Modified copy_arr:", copy_arr)



Original arr1: [ 1  2  3  4  5  6  7  8  9 10]
Modified copy_arr: [100   2   3   4   5   6   7   8   9  10]


# 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [62]:
import numpy as np

# Create a 2D NumPy array (matrix) of shape (3, 3) with random integers
matrix = np.random.randint(1, 10, size=(3, 3))
print("Original matrix:")
print(matrix)

# Extract a slice (view_slice) from the matrix
view_slice = matrix[1:, 1:]

# Modify an element in view_slice
view_slice[0, 0] = 100

# Observe if modifying view_slice changes the original matrix
print("\nModified view_slice:")
print(view_slice)

print("\nOriginal matrix after modification:")
print(matrix)


Original matrix:
[[5 5 7]
 [8 8 7]
 [2 4 1]]

Modified view_slice:
[[100   7]
 [  4   1]]

Original matrix after modification:
[[  5   5   7]
 [  8 100   7]
 [  2   4   1]]


# 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slicen `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [63]:
import numpy as np

# Create array_a with shape (4, 3) containing sequential integers from 1 to 12
array_a = np.arange(1, 13).reshape(4, 3)
print("Original array_a:")
print(array_a)

# Extract a slice (view_b) from array_a
view_b = array_a[1:3, 1:3]
print("\nSlice view_b from array_a:")
print(view_b)

# Broadcast addition of 5 to view_b
view_b += 5
print("\nModified view_b after addition:")
print(view_b)

# Check if it alters the original array_a
print("\nOriginal array_a after modification:")
print(array_a)


Original array_a:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Slice view_b from array_a:
[[5 6]
 [8 9]]

Modified view_b after addition:
[[10 11]
 [13 14]]

Original array_a after modification:
[[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 11 12]]


# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.

In [64]:
    import numpy as np

# Create orig_array with shape (2, 4) containing values from 1 to 8
orig_array = np.arange(1, 9).reshape(2, 4)
print("Original orig_array:")
print(orig_array)

# Create reshaped_view with shape (4, 2) from orig_array
reshaped_view = orig_array.reshape(4, 2)
print("\nReshaped view reshaped_view:")
print(reshaped_view)

# Modify an element in reshaped_view
reshaped_view[0, 0] = 100

# Check if it reflects changes in the original orig_array
print("\nModified reshaped_view:")
print(reshaped_view)

print("\nOriginal orig_array after modification:")
print(orig_array)


Original orig_array:
[[1 2 3 4]
 [5 6 7 8]]

Reshaped view reshaped_view:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Modified reshaped_view:
[[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]

Original orig_array after modification:
[[100   2   3   4]
 [  5   6   7   8]]


# 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [65]:
import numpy as np

# Create data with shape (3, 4) containing random integers
data = np.random.randint(1, 10, size=(3, 4))
print("Original data:")
print(data)

# Extract a copy data_copy of elements greater than 5 from data
data_copy = data[data > 5].copy()  # Use .copy() to create a separate copy

# Modify an element in data_copy
if data_copy.size > 0:
    data_copy[0] = 100

# Verify if modifying data_copy affects the original data
print("\nModified data_copy:")
print(data_copy)

print("\nOriginal data after modification:")
print(data)


Original data:
[[1 7 4 9]
 [9 2 4 4]
 [9 4 4 4]]

Modified data_copy:
[100   9   9   9]

Original data after modification:
[[1 7 4 9]
 [9 2 4 4]
 [9 4 4 4]]


# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

In [66]:
import numpy as np

# Create two matrices A and B of identical shape with integers
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])

# Perform addition and subtraction between A and B
addition_result = A + B
subtraction_result = A - B

# Print the results
print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nAddition result (A + B):")
print(addition_result)

print("\nSubtraction result (A - B):")
print(subtraction_result)


Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8  9]
 [10 11 12]]

Addition result (A + B):
[[ 8 10 12]
 [14 16 18]]

Subtraction result (A - B):
[[-6 -6 -6]
 [-6 -6 -6]]


# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [67]:
a = np.array([[1,2],[2,3],[1,2]])
b = np.array([[1,2,3,4],[1,2,3,5]])
print(a@b)

[[ 3  6  9 14]
 [ 5 10 15 23]
 [ 3  6  9 14]]


# 83. Create a matrix `E` and find its transpose.

In [68]:
E =  np.array([[1,2,3],[1,2,3],[2,3,4]])
print(E.T)

[[1 1 2]
 [2 2 3]
 [3 3 4]]


# 84. Generate a square matrix `F` and compute its determinant.

In [69]:
A = np.array([[1,2],[2,3]])
print(np.linalg.det(A))

-1.0


# 85. Create a square matrix `G` and find its inverse.

In [84]:
identity_matrix  = np.eye(2).astype("int")

In [85]:
identity_matrix

array([[1, 0],
       [0, 1]])

In [86]:
A = np.array([[1,2],[2,3]])
inverse_matrix = np.linalg.inv(A)
print(inverse_matrix)

[[-3.  2.]
 [ 2. -1.]]
